//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

// ignore_for_file: constant_identifier_names, use_super_parameters

import 'package:flutter/material.dart';

class FileType2 {
  static const String _family = 'icon-filetype2';
  
  FileType2._();
  
  static const IconData sort_z_a = IconData(0xe676, fontFamily: _family); // sort-z-a
  static const IconData sort_a_z = IconData(0xe679, fontFamily: _family); // sort-a-z
  static const IconData sort_asc = IconData(0xe7c6, fontFamily: _family); // sort-asc
  static const IconData sort_dasc = IconData(0xe7c7, fontFamily: _family); // sort-dasc
  static const IconData sort_1_9 = IconData(0xea07, fontFamily: _family); // sort-1-9
  static const IconData sort_9_1 = IconData(0xea08, fontFamily: _family); // sort-9-1
  static const IconData sort_time_down = IconData(0xe742, fontFamily: _family); // sort-time-down
  static const IconData sort_time_up = IconData(0xe7ba, fontFamily: _family); // sort-time-up
  static const IconData cn = IconData(0xe606, fontFamily: _family); // cn
  static const IconData en = IconData(0xe607, fontFamily: _family); // en
  static const IconData xterm = IconData(0xe864, fontFamily: _family); // xterm
  static const IconData node = IconData(0xe7a4, fontFamily: _family); // node
  static const IconData appimage = IconData(0xe610, fontFamily: _family); // appimage
  static const IconData xml = IconData(0xe600, fontFamily: _family); // xml
  static const IconData php = IconData(0xe681, fontFamily: _family); // php
  static const IconData sql = IconData(0xe69b, fontFamily: _family); // 文件类型
  static const IconData h = IconData(0xe680, fontFamily: _family); // h
  static const IconData hpp = IconData(0xe682, fontFamily: _family); // hpp
  static const IconData cpp = IconData(0xe660, fontFamily: _family); // CPP
  static const IconData sh = IconData(0xe62f, fontFamily: _family); // SH
  static const IconData yml = IconData(0xe631, fontFamily: _family); // YML
  static const IconData java = IconData(0xe601, fontFamily: _family); // java
  static const IconData pyc = IconData(0xe605, fontFamily: _family); // python
  static const IconData css = IconData(0xe612, fontFamily: _family); // CSS
  static const IconData json = IconData(0xe615, fontFamily: _family); // JSON
  static const IconData js = IconData(0xe616, fontFamily: _family); // JS
  static const IconData jar = IconData(0xe618, fontFamily: _family); // JAR
  static const IconData c = IconData(0xe630, fontFamily: _family); // c
  static const IconData py = IconData(0xe80a, fontFamily: _family); // pythonscrip
  static const IconData go = IconData(0xe709, fontFamily: _family); // go
  static const IconData vue = IconData(0xe633, fontFamily: _family); // vue
}

class _PreviewIcon {
  const _PreviewIcon(this.icon, this.name, this.propName);

  final IconData icon;
  final String name;
  final String propName;
}

class FileType2Preview extends StatelessWidget {
  const FileType2Preview({Key? key}) : super(key: key);

  static const iconList = <_PreviewIcon>[
    _PreviewIcon(FileType2.sort_z_a, "sort_z_a", "sort-z-a"),
    _PreviewIcon(FileType2.sort_a_z, "sort_a_z", "sort-a-z"),
    _PreviewIcon(FileType2.sort_asc, "sort_asc", "sort-asc"),
    _PreviewIcon(FileType2.sort_dasc, "sort_dasc", "sort-dasc"),
    _PreviewIcon(FileType2.sort_1_9, "sort_1_9", "sort-1-9"),
    _PreviewIcon(FileType2.sort_9_1, "sort_9_1", "sort-9-1"),
    _PreviewIcon(FileType2.sort_time_down, "sort_time_down", "sort-time-down"),
    _PreviewIcon(FileType2.sort_time_up, "sort_time_up", "sort-time-up"),
    _PreviewIcon(FileType2.cn, "cn", "cn"),
    _PreviewIcon(FileType2.en, "en", "en"),
    _PreviewIcon(FileType2.xterm, "xterm", "xterm"),
    _PreviewIcon(FileType2.node, "node", "node"),
    _PreviewIcon(FileType2.appimage, "appimage", "appimage"),
    _PreviewIcon(FileType2.xml, "xml", "xml"),
    _PreviewIcon(FileType2.php, "php", "php"),
    _PreviewIcon(FileType2.sql, "sql", "文件类型"),
    _PreviewIcon(FileType2.h, "h", "h"),
    _PreviewIcon(FileType2.hpp, "hpp", "hpp"),
    _PreviewIcon(FileType2.cpp, "cpp", "CPP"),
    _PreviewIcon(FileType2.sh, "sh", "SH"),
    _PreviewIcon(FileType2.yml, "yml", "YML"),
    _PreviewIcon(FileType2.java, "java", "java"),
    _PreviewIcon(FileType2.pyc, "pyc", "python"),
    _PreviewIcon(FileType2.css, "css", "CSS"),
    _PreviewIcon(FileType2.json, "json", "JSON"),
    _PreviewIcon(FileType2.js, "js", "JS"),
    _PreviewIcon(FileType2.jar, "jar", "JAR"),
    _PreviewIcon(FileType2.c, "c", "c"),
    _PreviewIcon(FileType2.py, "py", "pythonscrip"),
    _PreviewIcon(FileType2.go, "go", "go"),
    _PreviewIcon(FileType2.vue, "vue", "vue"),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('FileType2'),
      ),
      body: GridView.count(
        shrinkWrap: true,
        crossAxisCount: 4,
        children: iconList.map((e) {
          return InkWell(
            onTap: () {
              //
            },
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(
                  margin: const EdgeInsets.only(bottom: 8),
                  child: Icon(e.icon),
                ),
                Text(e.name, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                Text(e.propName, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
